Book: Introduction to Tensors and Group Theory for Physicists
Author: Nadir Jeevanjee
ISBN: 978-3319147932
Category: Maths
Subcategory: Linear Algebra
Tags: tensors,group theory
Name: Jeevanjee
SolutionAuthor: J. W. Kennington
